os:
  - linux
language: node_js

node_js:
  - "node"
  - "10"
  - "9"
  - "8"

before_script:
  - npm i -g typescript
  - npm i

script:
  - npm run build:clean

jobs:
  include:
    - stage: "Deploy"
      deploy:
        provider: npm
        email: $NPM_EMAIL_ADDR
        api_key: $NPM_API_KEY
        skip_cleanup: true
        on:
          tags: true
          branch: master

notifications:
  email:
    recipients:
    - lucas.santos@nxcd.com.br
    - rogerio.munhoz@nxcd.com.br
    on_success: change
    on_failure: always